### ISSUE TITLE
logica proposicional

### ISSUE THREAD

**Issue by W1ll1am21** [SistemasTecTlaxiaco/actividad-7-proposiciones-l-gicas-W1ll1am21#1]
[logica proposicional.pdf](https://github.com/user-attachments/files/17440681/logica.proposicional.pdf)

**Comment by irwingsael** [comment]
Portada:25/25
Procedimiento:25/25
Figuras, Ilustraciones y Fotografías:25/25
Resultados y conclusiones:25/25
Total:100/100
20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
